"""
Terms of Service and Legal text for the game.

This text is presented in-game from the Settings screen. It is written for a
free, fan-made hobby project and is provided for informational purposes only.
It is not legal advice. The text is rendered as a list of lines/paragraphs;
blank strings are used to create vertical spacing between sections.
"""

GAME_NAME = "JIN"
GAME_VERSION = "v2.4.0 - Enhanced Edition"

TOS_TEXT = [
    "TERMS OF SERVICE",
    "Last updated: June 2026",
    "",
    "Welcome, and thanks for playing! By downloading, launching, or",
    "playing this game you agree to the terms described below. If you do",
    "not agree with any part of these terms, please do not play the game.",
    "",
    "1. ACCEPTANCE OF TERMS",
    "This game is a free, fan-made hobby project created for entertainment",
    "and educational purposes. Continuing past this screen and playing the",
    "game means you accept these Terms of Service in full.",
    "",
    "2. LICENSE TO PLAY",
    "You are granted a personal, non-exclusive, non-transferable, revocable",
    "license to install and play the game on devices you own or control,",
    "strictly for non-commercial personal use. You may not sell, rent, or",
    "charge others for access to the game.",
    "",
    "3. ACCEPTABLE USE",
    "You agree not to:",
    "  - Use the game for any unlawful or harmful purpose.",
    "  - Distribute modified versions claiming to be the original game.",
    "  - Attempt to cheat in ways that harm other players' experience.",
    "  - Remove or obscure any credit or attribution notices.",
    "",
    "4. USER CONDUCT AND FAIR PLAY",
    "High scores are stored locally on your own device. Tampering with save",
    "files only affects your own copy of the game. Please play fair and have",
    "fun. We are not responsible for lost progress or corrupted save data.",
    "",
    "5. NO WARRANTY",
    "The game is provided \"AS IS\" and \"AS AVAILABLE\" without warranties",
    "of any kind, whether express or implied, including but not limited to",
    "fitness for a particular purpose and non-infringement. We do not",
    "guarantee the game will be error-free or run on every system.",
    "",
    "6. LIMITATION OF LIABILITY",
    "To the fullest extent permitted by law, the creators of this game shall",
    "not be liable for any damages arising from your use of, or inability to",
    "use, the game. You play at your own risk.",
    "",
    "7. UPDATES AND CHANGES",
    "The game and these terms may be updated from time to time. Continued",
    "play after changes are made constitutes acceptance of the revised terms.",
    "",
    "8. TERMINATION",
    "You may stop playing and delete the game at any time. Your license ends",
    "automatically if you breach any of these terms.",
    "",
    "9. CONTACT",
    "This is an independent hobby project. For questions about these terms,",
    "please refer to the project's README file or repository page.",
    "",
    "Thanks for reading, and enjoy the adventure!",
]

LEGAL_TEXT = [
    "LEGAL & ATTRIBUTIONS",
    "Last updated: June 2026",
    "",
    "COPYRIGHT",
    "This game, including its original source code, level design, and",
    "original artwork generated for this project, is the work of its",
    "creator. All rights reserved unless otherwise stated.",
    "",
    "FAN PROJECT DISCLAIMER",
    "This is an unofficial, non-commercial fan-made game inspired by the",
    "classic 2D platformer genre. It is not affiliated with, endorsed by,",
    "sponsored by, or associated with Nintendo Co., Ltd. or any other",
    "company. \"Mario\" and all related names, characters, and trademarks",
    "are the property of their respective owners. No copyrighted character",
    "art or assets owned by those companies are intentionally included.",
    "",
    "TRADEMARKS",
    "All product names, logos, and brands mentioned anywhere in this game",
    "or its documentation are the property of their respective owners. Use",
    "of these names does not imply any affiliation or endorsement.",
    "",
    "OPEN SOURCE SOFTWARE",
    "This game is built using the Pygame library, which is distributed",
    "under the GNU Lesser General Public License (LGPL). Pygame is built",
    "on top of the SDL library. We gratefully acknowledge the Pygame and",
    "SDL communities for their excellent open-source work.",
    "",
    "MUSIC AND SOUND",
    "Sound effects and music cues used in this game are procedurally",
    "generated or are believed to be free for non-commercial use. If you",
    "believe any asset has been used incorrectly, please reach out so it",
    "can be reviewed and removed if necessary.",
    "",
    "PRIVACY",
    "This game runs entirely on your local device. It does not collect,",
    "transmit, or sell any personal data. The only information saved is",
    "your high score, which is stored in a local file on your computer.",
    "Optional Discord Rich Presence, if enabled, shares your game status",
    "with Discord according to Discord's own privacy policy.",
    "",
    "THIRD-PARTY SERVICES",
    "If Discord integration is active, your interaction with Discord is",
    "governed by Discord's Terms of Service and Privacy Policy. We are not",
    "responsible for the practices of any third-party service.",
    "",
    "NO WARRANTY",
    "This software is provided \"as is\", without warranty of any kind,",
    "express or implied. In no event shall the authors be liable for any",
    "claim, damages, or other liability arising from the software.",
    "",
    "DMCA / TAKEDOWN",
    "This project respects intellectual property rights. If you are a",
    "rights holder and believe content infringes your rights, a good-faith",
    "request for removal will be honored promptly.",
    "",
    "Made with care by a fan, for fans. Thank you for playing!",
]
