import pygame
from constants import COLOR_MAP

SMALL_MARIO_IDLE = [
    "....rrrrr...",
    "...rrrrrrrr.",
    "...kkkssks..",
    "..ksskskkks.",
    "..ksskskks..",
    "..kksssks...",
    "...ssssss...",
    "..rbrrrbr...",
    ".rrbrrrbrr..",
    "rrrbbbbbbrrr",
    "wwbbbyybbbyw",
    "wwbbbbbbbbww",
    ".bbbb..bbbb.",
    ".kkk....kkk.",
    "kkk......kkk",
    "............",
]

SMALL_MARIO_WALK1 = [
    "....rrrrr...",
    "...rrrrrrrr.",
    "...kkkssks..",
    "..ksskskkks.",
    "..ksskskks..",
    "..kksssks...",
    "...ssssss...",
    "..rbrrrbr...",
    ".rrbrrrbrr..",
    "rrrbbbbbbrrr",
    "wwbbbyybbbyw",
    "wwbbbbbbbbww",
    "..bbbbbbbb..",
    "...kkk.kk...",
    "..kkk...kk..",
    "............",
]

SMALL_MARIO_WALK2 = [
    "....rrrrr...",
    "...rrrrrrrr.",
    "...kkkssks..",
    "..ksskskkks.",
    "..ksskskks..",
    "..kksssks...",
    "...ssssss...",
    "..rbrrrbr...",
    ".rrbrrrbrr..",
    "rrrbbbbbbrrr",
    "wwbbbyybbbyw",
    "wwbbbbbbbbww",
    "..bbb..bb...",
    "..kk....kk..",
    ".kkk....kkk.",
    "............",
]

SMALL_MARIO_JUMP = [
    "....rrrrr...",
    "...rrrrrrrr.",
    "...kkkssks..",
    "..ksskskkks.",
    "..ksskskks..",
    "..kksssks...",
    "...ssssss...",
    "..rrbrrrbr..",
    ".w.rbrrrbr.w",
    "wwrrbbbbbrrww",
    "wwbbbyybbbww",
    ".bbbbbbbbbb.",
    "..bbb..bbb..",
    ".kkk....kkk.",
    "kkk......kkk",
    "............",
]

SMALL_MARIO_DUCK = [
    "............",
    "............",
    "....rrrrr...",
    "...rrrrrrrr.",
    "...kkkssks..",
    "..ksskskkks.",
    "..kksssks...",
    "...ssssss...",
    "..rbrrrbr...",
    "rrrbbbbbbrrr",
    "wwbbbyybbbyw",
    ".kkk....kkk.",
]

BIG_MARIO_IDLE = [
    "......rrrrr.....",
    ".....rrrrrrrr...",
    ".....kkkssks....",
    "....ksskskkks...",
    "....ksskskks....",
    "....kksssks.....",
    ".....ssssss.....",
    "....rrbrrrbr....",
    "...rrrbrrrbrr...",
    "..rrrrbrrrbrrr..",
    "..wwrrbbbbbrrww.",
    "..wwrbbbbbbbrww.",
    "..wwbbbyybbbyww.",
    "...bbbbbbbbbbb..",
    "...bbbbbbbbbbb..",
    "...bbbb...bbbb..",
    "..kkkk.....kkkk.",
    "..kkkk.....kkkk.",
    ".kkkkk.....kkkkk",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
]

BIG_MARIO_WALK1 = [
    "......rrrrr.....",
    ".....rrrrrrrr...",
    ".....kkkssks....",
    "....ksskskkks...",
    "....ksskskks....",
    "....kksssks.....",
    ".....ssssss.....",
    "....rrbrrrbr....",
    "...rrrbrrrbrr...",
    "..rrrrbrrrbrrr..",
    "..wwrrbbbbbrrww.",
    "..wwrbbbbbbbrww.",
    "..wwbbbyybbbyww.",
    "...bbbbbbbbbbb..",
    "...bbbbbbbbbbb..",
    "....bbbbbbbbb...",
    "....kkkkkkkk....",
    "....kkk..kkk....",
    "....kk....kk....",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
]

BIG_MARIO_WALK2 = [
    "......rrrrr.....",
    ".....rrrrrrrr...",
    ".....kkkssks....",
    "....ksskskkks...",
    "....ksskskks....",
    "....kksssks.....",
    ".....ssssss.....",
    "....rrbrrrbr....",
    "...rrrbrrrbrr...",
    "..rrrrbrrrbrrr..",
    "..wwrrbbbbbrrww.",
    "..wwrbbbbbbbrww.",
    "..wwbbbyybbbyww.",
    "...bbbbbbbbbbb..",
    "...bbbbbbbbbbb..",
    "....bbbb.bbbb...",
    "....kkk...kkkk..",
    "....kk.....kkkk.",
    "....kk......kkk.",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
]

BIG_MARIO_JUMP = [
    "......rrrrr.....",
    ".....rrrrrrrr...",
    ".....kkkssks....",
    "....ksskskkks...",
    "....ksskskks....",
    "....kksssks.....",
    ".....ssssss.....",
    "....rrbrrrbr....",
    "...rrrbrrrbrr...",
    "..rrrrbrrrbrrr..",
    "..wwrrbbbbbrrww.",
    "..wwrbbbbbbbrww.",
    "..wwbbbyybbbyww.",
    "...bbbbbbbbbbb..",
    "...bbbbbbbbbbb..",
    "...bbbb...bbbb..",
    "..kkkk.....kkkk.",
    "..kkkk.....kkkk.",
    ".kkkk.......kkk.",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
]

BIG_MARIO_DUCK = [
    "................",
    "................",
    "................",
    "................",
    "................",
    "......rrrrr.....",
    ".....rrrrrrrr...",
    ".....kkkssks....",
    "....ksskskkks...",
    "....kksssks.....",
    ".....ssssss.....",
    "....rrbrrrbr....",
    "...rrrbrrrbrr...",
    "..wwrrbbbbbrrww.",
    "..wwrbbbbbbbrww.",
    "..wwbbbyybbbyww.",
    "...bbbbbbbbbbb..",
    "...bbbbbbbbbbb..",
    "....kkk...kkk...",
    "....kkk...kkk...",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
]

GOOMBA_WALK1 = [
    ".....kkkkkk.....",
    "....kkkkkkkk....",
    "...kkkkkkkkkk...",
    "..kkkkkkkkkkkk..",
    ".kkkewkkkkewkkk.",
    ".kkkewkkkkewkkk.",
    "kkkkewkkkkewkkkk",
    "kkkkkkeeeekkkkkk",
    "kkkksssssssskkkk",
    ".kksssssssssskk.",
    "..ssssssssssss..",
    "...ssssssssss...",
    "....eeeee.eeee..",
    "....eeeee.eeee..",
    "....eeee...eee..",
    "................",
]

GOOMBA_WALK2 = [
    ".....kkkkkk.....",
    "....kkkkkkkk....",
    "...kkkkkkkkkk...",
    "..kkkkkkkkkkkk..",
    ".kkkewkkkkewkkk.",
    ".kkkewkkkkewkkk.",
    "kkkkewkkkkewkkkk",
    "kkkkkkeeeekkkkkk",
    "kkkksssssssskkkk",
    ".kksssssssssskk.",
    "..ssssssssssss..",
    "...ssssssssss...",
    ".....eeee.eeeee.",
    ".....eeee.eeeee.",
    "......eee...eee.",
    "................",
]

GOOMBA_SQUISHED = [
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    "................",
    ".....kkkkkk.....",
    "....kkkkkkkk....",
    "...kkewkkewkk...",
    "..kkkewkkewkkk..",
    ".kkkkkkeeeekkkk.",
    "kkkksssssssskkkk",
    "ssssssssssssssss",
    "eeeeeeeeeeeeeeee",
]

KOOPA_WALK1 = [
    "......gggggg....",
    ".....gggggggg...",
    "....gggewwewgg..",
    "....gggewwewgg..",
    "....ggggsseegg..",
    ".....ssssssss...",
    "......ssssss....",
    "....yygggyyy....",
    "...yyygggggyy...",
    "..yyyygggggyyy..",
    "..yyygggggggyy..",
    "..yygggggggggy..",
    "..yggggggggggy..",
    "..yggggggggggy..",
    "..yggggggggggy..",
    "..yyggggggggyy..",
    "...gggggggggg...",
    "....gggggggg....",
    "....yyyy..yyy...",
    "....yyyy..yyy...",
    "....sss....sss..",
    "....sss....sss..",
    "................",
    "................",
]

KOOPA_WALK2 = [
    "......gggggg....",
    ".....gggggggg...",
    "....gggewwewgg..",
    "....gggewwewgg..",
    "....ggggsseegg..",
    ".....ssssssss...",
    "......ssssss....",
    "....yygggyyy....",
    "...yyygggggyy...",
    "..yyyygggggyyy..",
    "..yyygggggggyy..",
    "..yygggggggggy..",
    "..yggggggggggy..",
    "..yggggggggggy..",
    "..yggggggggggy..",
    "..yyggggggggyy..",
    "...gggggggggg...",
    "....gggggggg....",
    ".....yyy..yyyy..",
    ".....yyy..yyyy..",
    ".....sss..sss...",
    ".....sss..sss...",
    "................",
    "................",
]

KOOPA_SHELL = [
    "................",
    "................",
    "................",
    "................",
    "......gggggg....",
    "....gggggggggg..",
    "...gggggggggggg.",
    "..gggyygggyygggy",
    ".ggyyyyyyyyyyyyg",
    ".gyyyyyyyyyyyyyg",
    ".gyyggggggggyyyg",
    "ggyggggggggggyyg",
    "ggyggggggggggyyg",
    "ggyggggggggggyyg",
    "ggyggggggggggyyg",
    ".gyyggggggggyyyg",
    ".gyyyyyyyyyyyyyg",
    ".ggyyyyyyyyyyyyg",
    "..gggyygggyygggy",
    "...gggggggggggg.",
    "....gggggggggg..",
    "......gggggg....",
    "................",
    "................",
]

BLOCK_GROUND = [
    "kkkkkkkkkkkkkkko",
    "kpppppppppppppok",
    "kpppppppppppppok",
    "kpppppppppppppok",
    "kpppppppppppppok",
    "kpppppppppppppok",
    "kpppppppppppppok",
    "kpppppppppppppok",
    "kpppppppppppppok",
    "kpppppppppppppok",
    "kpppppppppppppok",
    "kpppppppppppppok",
    "kpppppppppppppok",
    "kpppppppppppppok",
    "kpppppppppppppok",
    "okkkkkkkkkkkkkko",
]

BLOCK_BRICK = [
    "oooooooooooooooo",
    "opppppppoopppppp",
    "opppppppoopppppp",
    "oooooooooooooooo",
    "ppppooppppppoopp",
    "ppppooppppppoopp",
    "oooooooooooooooo",
    "opppppppoopppppp",
    "opppppppoopppppp",
    "oooooooooooooooo",
    "ppppooppppppoopp",
    "ppppooppppppoopp",
    "oooooooooooooooo",
    "opppppppoopppppp",
    "opppppppoopppppp",
    "oooooooooooooooo",
]

BLOCK_QUESTION_F1 = [
    "eeeeeeeeeeeeeeee",
    "eyyyyyyyyyyyyyye",
    "eyyyyyyyyyyyyyye",
    "eyyyyeeeeeeeyyye",
    "eyyyeewwewweeyye",
    "eyyyeeweeeweeyye",
    "eyyyeeeeeweeeyye",
    "eyyyyyyyeweeeyye",
    "eyyyyyyeweeeeyye",
    "eyyyyyyeweeeeyye",
    "eyyyyyyyeeeeeyye",
    "eyyyyyyeweeeeyye",
    "eyyyyyyeweeeeyye",
    "eyyyyyyyyyyyyyye",
    "eyyyyyyyyyyyyyye",
    "eeeeeeeeeeeeeeee",
]

BLOCK_QUESTION_F2 = [
    "eeeeeeeeeeeeeeee",
    "eoooooooooooeeoe",
    "eoyyyyyyyyyyooye",
    "eoyyyeeeeeeoyooe",
    "eoyyyeewwewweooe",
    "eoyyyeeweeeweooe",
    "eoyyyeeeeeweoooe",
    "eoyyyyyyyewooooe",
    "eoyyyyyyewoooooe",
    "eoyyyyyyewoooooe",
    "eoyyyyyyyooooooe",
    "eoyyyyyyewoooooe",
    "eoyyyyyyewoooooe",
    "eoyyyyyyyyyooooe",
    "eooooooooooooooe",
    "eeeeeeeeeeeeeeee",
]

BLOCK_SOLID = [
    "dddddddddddddddd",
    "dlllllllllllllld",
    "dlddddddddddddld",
    "dlddddddddddddld",
    "dlddddddddddddld",
    "dlddddddddddddld",
    "dlddddddddddddld",
    "dlddddddddddddld",
    "dlddddddddddddld",
    "dlddddddddddddld",
    "dlddddddddddddld",
    "dlddddddddddddld",
    "dlddddddddddddld",
    "dlddddddddddddld",
    "dlllllllllllllld",
    "dddddddddddddddd",
]

BLOCK_SPIKE = [
    "..e..e..e..e..e.",
    "..e..e..e..e..e.",
    ".lel.lel.lel.lel",
    ".lel.lel.lel.lel",
    "lelelelelelelele",
    "lelelelelelelele",
    "leeleeleeleeleel",
    "llllllllllllllll",
    "ldddddddddddddl.",
    "ldlllllllllllld.",
    "ldlddddddddddld.",
    "ldlddddddddddld.",
    "ldlddddddddddld.",
    "ldlllllllllllld.",
    "lddddddddddddld.",
    "dddddddddddddddd",
]

ITEM_MUSHROOM = [
    ".....rrrr......",
    "...rrrrrrrr....",
    "..rrwwrrwwrr...",
    ".rrwwwwwwwwrr..",
    ".rrwwwwwwwwrr..",
    ".rwwrwwwwrwwr..",
    "rwwrrrrrrrwwr..",
    "rwwrrrrrrrwwr..",
    "rrrrrrrrrrrrrr.",
    "..ssssssssss...",
    "..ssseeeesss...",
    "..ssseeeesss...",
    "..ssssssssss...",
    "..ssssssssss...",
    "...ssssssss....",
    "................",
]

ITEM_COIN_F1 = [
    ".....eeee......",
    "...eeyyyyee....",
    "..eeyyyyyyee...",
    ".eeyyeyyeyyee..",
    ".eeyyeyyeyyee..",
    "eeyyeyyeyyeyyee",
    "eeyyeyyeyyeyyee",
    "eeyyeyyeyyeyyee",
    "eeyyeyyeyyeyyee",
    "eeyyeyyeyyeyyee",
    ".eeyyeyyeyyee..",
    ".eeyyeyyeyyee..",
    "..eeyyyyyyee...",
    "...eeyyyyee....",
    ".....eeee......",
    "................",
]

ITEM_COIN_F2 = [
    "......ee......",
    "....eeyyee....",
    "...eeyyyyee...",
    "..eeyeyyeyee..",
    "..eeyeyyeyee..",
    "..eeyeyyeyee..",
    "..eeyeyyeyee..",
    "..eeyeyyeyee..",
    "..eeyeyyeyee..",
    "..eeyeyyeyee..",
    "..eeyeyyeyee..",
    "..eeyeyyeyee..",
    "...eeyyyyee...",
    "....eeyyee....",
    "......ee......",
    "..............",
]

FLAG = [
    "gggggggggggggggg",
    "gwwwwwwwwwwwwwwg",
    "gwwwwwrrwwwwwwwg",
    "gwwwwrrrrwwwwwwg",
    "gwwwrrrrrrwwwwwg",
    "gwwrrrrrrrrwwwwg",
    "gwrrrrrrrrrrwwwg",
    "gwrrrrrrrrrrwwwg",
    "gwwrrrrrrrrwwwwg",
    "gwwwrrrrrrwwwwwg",
    "gwwwwrrrrwwwwwwg",
    "gwwwwwrrwwwwwwwg",
    "gwwwwwwwwwwwwwwg",
    "gggggggggggggggg",
    "................",
    "................",
]


def make_sprite(pixel_data, scale=2, color_override=None, flip_x=False):
    h = len(pixel_data)
    w = len(pixel_data[0]) if h > 0 else 0
    surf = pygame.Surface((w * scale, h * scale), pygame.SRCALPHA)

    for y in range(h):
        for x in range(w):
            char = pixel_data[y][x]
            if char in COLOR_MAP and char != '.':
                color = color_override if color_override else COLOR_MAP[char]
                pygame.draw.rect(surf, color, (x * scale, y * scale, scale, scale))

    if flip_x:
        surf = pygame.transform.flip(surf, True, False)
    return surf
